### ISSUE TITLE
[Epic] Mobile SDKs asessment

### ISSUE THREAD

**Issue by justinbarry** [onflow/sdks#15]
# Description
Deep dive into existing mobile SDKs, current state, and maintainers.

# Definition of done
A document listing all available Mobile SDK Options for the community, the relevant maintainer(s), and any deficiencies in said SDKs. 

```[tasklist]
### Tasks
- [x] Create Document to showcase SDK options (Likely to live in dev portal but needs to be public facing)
- [ ] Find and create tasks for iOS SDKs
- [ ] Find and create tasks for Android SDKs
- [ ] Find and create tasks for Unity SDKs
```
